### ISSUE TITLE
Error:Cannot compare value: java-runtime

### ISSUE THREAD

**Issue by javanyou** [wupdigital/android-maven-publish#10]
apply plugin: 'digital.wup.android-maven-publish'
    publishing {
        publications {
            mavenAar(MavenPublication) {
                 from components.android
            }
        }
    }

When I add code above to my android library project, I got error .

20:22:16.486 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: com.google.common.collect.Ordering$IncomparableValueException: Cannot compare value: java-runtime
20:22:16.487 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.common.collect.ExplicitOrdering.rank(ExplicitOrdering.java:46)
20:22:16.487 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.common.collect.ExplicitOrdering.compare(ExplicitOrdering.java:40)
20:22:16.487 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication$1.compare(DefaultMavenPublication.java:74)

How can I solve this problem ?

**Comment by warnyul** [comment]
Could you please provide more information? Which android maven plugin version, which Gradle version and which android build tools version are you using?

**Comment by javanyou** [comment]
@warnyul   Thank you for replay. :)

I add below code to my project root dir build.gradle file.

    buildscript {
        repositories {
            jcenter()
        }
        dependencies {
            classpath 'digital.wup:android-maven-publish:3.1.1'
        }
    }

My gradle version was 4.1 which android studio change itself . I have run your plugin test file, and debug it, everything is right. The problem has been bothering me for two days.

android buildToolsVersion = 26.0.2
Do I need apply plugin maven-push by myself?

**Comment by javanyou** [comment]
I change android-maven-publish version to 3.0.0 is right. thank you, This is my problem
