### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by kkovach** [wupdigital/android-maven-publish#12]
This seems pretty straight forward, but apparently I'm not understanding something or am missing something. I've added the plugin to my android library and tried to test by publishing to maven local and am getting the following error.

> Could not get unknown property 'android' for SoftwareComponentInternal set of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.

My build.gradle file has the following in it.

publishing.publications {
  mavenAar(MavenPublication) {
    from components.android
  }
}

Thanks in advance for any advice or suggestions.

**Comment by warnyul** [comment]
Two cases are possible:
* You applied the plugin in an application module. This plugin doesn't support android application modules.
* You applied before apply the android library module. Try to apply maven publish plugin after android library plugin

**Comment by warnyul** [comment]
I plan to do a sample project as soon as possible. I hope it will help you.
