### ISSUE TITLE
Gradle 4.6

### ISSUE THREAD

**Issue by Dkhusainov** [wupdigital/android-maven-publish#14]
Hello.

I've tried using it with gradle new [BOM support](https://docs.gradle.org/4.6/release-notes.html#bom-import) but it produces pom with versions absent from dependencies. 

Example:

`compile "org.jetbrains.kotlin:kotlin-stdlib"`(version is derived from BOM)
produces this
   `<dependency> 
     <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib</artifactId>
    </dependency>
`

**Comment by warnyul** [comment]
It seems to be valid. Gradle resolves versions from BOM during build time.

**Comment by Dkhusainov** [comment]
Is there a way to make it resolve versions for POM?

**Comment by warnyul** [comment]
Resolve versions from BOM manually is currently yet supported in Gradle. Spring has a project [here](https://github.com/spring-gradle-plugins/dependency-management-plugin), this maybe solve your problem. But I think it will be deprecated after Gradle 5.0. Why do you want the version to be included in the POM file, when it is derived from BOM?

**Comment by Dkhusainov** [comment]
Because the consumer of the artifact might not yet support new gradle/BOM versioning. Which is my case exactly.

**Comment by warnyul** [comment]
The `android-maven-publish` is a modification of the standard Maven Publish plugin. I don't want to change how write the pom file. I wondered how to solve the problem.

First I tried to resolve versions in the `resolutionStrategy` closure. As a result, I found [GRADLE-3120](https://issues.gradle.org/browse/GRADLE-3120). It does not work, but the Gradle provides an api to request resolved versions. It's a little bit ugly, but works:

```
def getResolvedVersionOf(group, name) {
    return configurations.releaseRuntimeClasspath.resolvedConfiguration.firstLevelModuleDependencies.asList().find { e ->
        if (e.moduleGroup == group && e.moduleName == name) {
            return e
        }
    }?.moduleVersion
}

publishing {
    publications {
        aar(MavenPublication) {
            from components.android

            pom.withXml {
                Node pomNode = asNode()

                pomNode.dependencies.first().children().each { dependencyNode ->

                    // version node is not found in pom
                    if (!dependencyNode.get('version')) {

                        def groupId = dependencyNode.get('groupId').text()
                        def artifactId = dependencyNode.get('artifactId').text()
                        def version = getResolvedVersionOf(groupId, artifactId)

                        if (version) {
                            // Append resolved version
                            dependencyNode.appendNode('version', version)
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by Dkhusainov** [comment]
Looks good, thanks. WIll use this.
