### ISSUE TITLE
POM file contains packaging as "pom" instead of "aar"

### ISSUE THREAD

**Issue by rahulsh12** [wupdigital/android-maven-publish#26]
My gradle looks like this for publishing the library to a private maven repository using artifactory

```
publishing {
    publications {
        aar(MavenPublication) {
            from components.android

            groupId libraryGroupId
            version libraryVersion
            artifactId libraryArtifactId

            artifact("$buildDir/outputs/aar/${artifactId}-release.aar")
        }
    }
}

artifactory {
    contextUrl = repoUrl
    publish {
        repository {
            repoKey = 'libs-release-local'

            username = artifactory_username
            password = artifactory_password
        }
        defaults {
            publications('aar')
            publishArtifacts = true

            properties = ['qa.level': 'basic', 'q.os': 'android', 'dev.team': 'core']
            publishPom = true
        }
    }
}
```

There are 2 issues currently
1. The POM file generated has property `<packaging>pom</packaging>` instead of `<packaging>aar</packaging>`. The dependencies are generated fine. 
2. When using the library in a project, the AAR file is downloaded correctly by gradle but the POM file is not downloaded and hence the transitive dependencies are not resolved.

The app implementing the library crashes on runtime due to missing runtime dependencies.

Gradle version: 4.4

**Comment by warnyul** [comment]
You should remove `artifact("$buildDir/outputs/aar/${artifactId}-release.aar")` line, because you override the artifact which has been provided by the plugin. This will solve your first problem.

**Comment by warnyul** [comment]
If you want to define transitive dependencies, you will define with `api` configuration instead of `implementation`
