### ISSUE TITLE
Gradle sync fails after adding plugin on a brand new android library

### ISSUE THREAD

**Issue by provenstyle** [wupdigital/android-maven-publish#29]
Unable to load class 'org.gradle.api.capabilities.Capability'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)</li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)</li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by warnyul** [comment]
Please add the Grade and the plugin version. Maybe your Gradle version is incompatible with the plugin.

**Comment by provenstyle** [comment]
You are right.  I realize the importance of the compatibility table now.  I was trying to use  Gradle 4.6 with 3.6.2 and they are incompatible. Thank you.

**Comment by warnyul** [comment]
No problem. Unfortunately it's important, because maven-publish is an incubation feature in Gradle. It will be stable in Gradle 5.0
