### ISSUE TITLE
Compatibility with Gradle 5.0

### ISSUE THREAD

**Issue by pavel163** [wupdigital/android-maven-publish#30]
I have problems in this part of code 
```groovy
publications {
            mavenAar(MavenPublication) {
                from components.android

                artifact javadocsJar
                artifact sourcesJar
            }
        }
```

> > Failed to notify project evaluation listener.
   > Could not get unknown property 'javadocsJar' for object of type org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.
   > java.lang.reflect.InvocationTargetException (no error message)
 and
> > Failed to notify project evaluation listener.
   > Could not get unknown property 'sourcesJar' for object of type org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.
   > java.lang.reflect.InvocationTargetException (no error message)

**Comment by warnyul** [comment]
I think the LazyPublishArtifact solves the problem. I close it.

**Comment by alixwar** [comment]
Note that the project mentioned above does not use Gradle 5: https://github.com/trevjonez/android-components-plugin/blob/c69bbfda144978b198631a0164b3ae88444d4027/gradle/wrapper/gradle-wrapper.properties

LazyPublishArtifact doesn't exist in Gradle 5.3.1 at least: https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/dsl/package-summary.html

**Comment by trevjonez** [comment]
Lazy publish artifact is internal API that we should not be using at all (although no better option really). internal API's are not listed in javadoc.
