### ISSUE TITLE
Issues with POMs and Android Gradle 3.0 

### ISSUE THREAD

**Issue by hameno** [wupdigital/android-maven-publish#4]
I just tried this plugin and found the following issues with Android Gradle 3.0 (not sure if it works correctly with 2.3.3)

1) "type" is missing for aar dependencies, e.g.
```api project(':library')```
produces
```
<dependency>
  <groupId>project-group</groupId>
  <artifactId>library</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <scope>compile</scope>
</dependency>
```

It should be 

```
<dependency>
  <groupId>project-group</groupId>
  <artifactId>library</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <scope>compile</scope>
  <type>aar</type>
</dependency>
```

2) scope is wrong for dependencies, e.g.

```
    implementation group: 'com.android.support', name: 'support-v4', version: project.ext.supportLibVersion
```` 
produces 

```` 
<dependency>
  <groupId>com.android.support</groupId>
  <artifactId>support-v4</artifactId>
  <version>26.1.0</version>
  <scope>runtime</scope>
</dependency>
```` 

As you can see above the scope is set to runtime, but it should be compile. (also type is missing here too)
see https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope (runtime will not be used for compilation)

**Comment by hameno** [comment]
Okay, seems I misunderstood how api / implementation works. 2) seems to be correct.
Now, for a valid pom only the type is missing. any idea on how to add that?

**Comment by warnyul** [comment]
Could you please send your maven-publish plugin configuration?

**Comment by hameno** [comment]
Should be irrelevant, since then I found that it is a gradle issue (https://github.com/gradle/gradle/issues/3170) thats causing this - they simply don't support generating correct poms with type information.

**Comment by warnyul** [comment]
I think this is not a bug. It is the original behavior of maven-publish plugin. You can specify the type of dependency manually: 

`implementation "com.android.support:support-v4:${project.ext.supportLibVersion}@aar"`

**Comment by Alireza-Farahani** [comment]
I'm using version 3.1.1 of plugin and still it converts `Implementation` scope to `runtime` in generated POM file.

**Comment by warnyul** [comment]
This is the expected behavior. If you want to add dependencies with `compile` scope for POM file, you can use `api` configuration.  Read the releaded [documentation](https://docs.gradle.org/current/userguide/java_library_plugin.html).
