### ISSUE TITLE
publish android library with values-night

### ISSUE THREAD

**Issue by fakeguy256** [wupdigital/android-maven-publish#44]
I am working on a library which provides a theme,
A common theme for all apps made by us.
So I want to export values-night as well as values to the aar file.
I can publish my package to github packages and everything is working fine except values and values-night aren't added to aar.

I am having following error / warning when I am assembling the module.

```
D:\common\common\build\intermediates\res\merged\release\values-night-v8\values-night-v8.xml:10: warn: i
gnoring configuration 'night-v8' for attribute attr/toolbar_text_secondary.
```

**Comment by fakeguy256** [comment]
It merges all my attrs.xml and themes.xml in to one file 

as follows -

`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <attr format="color" name="backgroundcolor"/>
    <attr format="color" name="polu"/>
    <attr format="color" name="statusbarcolor"/>
    <attr format="color" name="textcolor"/>
    <attr format="color" name="textcolor2"/>
    <attr format="color" name="toolbar_color"/>
    <attr format="color" name="toolbar_text"/>
    <attr format="color" name="toolbar_text_secondary"/>
    <color name="close_background">#FAFAFA</color>
    <color name="dark1">#424242</color>
    <color name="dark2">#303030</color>
    <color name="dark3">#212121</color>
    <color name="dark_google">#202125</color>
    <color name="gray">#607d8b</color>
    <color name="pink">#D81B60</color>
    <color name="purple_200">#FFBB86FC</color>
    <color name="purple_500">#FF6200EE</color>
    <color name="purple_700">#FF3700B3</color>
    <color name="teal_200">#FF03DAC5</color>
    <color name="teal_700">#FF018786</color>
    <style name="CommonAppTheme" parent="Theme.MaterialComponents.DayNight.NoActionBar">
        
        <item name="toolbar_color">@color/dark3</item>
        <item name="toolbar_text">@android:color/white</item>
        <item name="backgroundcolor">@color/dark1</item>
        <item name="toolbar_text_secondary">@android:color/white</item>
        <item name="textcolor">@android:color/black</item>
        <item name="textcolor2">@android:color/white</item>
        <item name="statusbarcolor">?toolbar_color</item>
        
        <item name="colorPrimary">@color/purple_500</item>
        <item name="colorPrimaryVariant">@color/purple_700</item>
        <item name="colorPrimaryDark">@color/purple_500</item>
        <item name="colorAccent">@color/purple_500</item>
        <item name="colorOnPrimary">@android:color/white</item>
        <item name="colorSecondary">@color/teal_200</item>
        <item name="colorSecondaryVariant">@color/teal_700</item>
        <item name="colorOnSecondary">@android:color/black</item>
        
        <item name="android:textColor">?textcolor</item>
        <item name="android:textColorPrimary">?textcolor</item>
        <item name="android:textColorSecondary">?toolbar_text_secondary</item>
        <item name="android:statusBarColor">?statusbarcolor</item>
        <item name="android:colorBackground">?backgroundcolor</item>
    </style>
</resources>`

**Comment by warnyul** [comment]
This plugin does not make any changes on the aar file. Maybe something else is causing the problem.

However, this plugin is no longer supported. Please use the maven-publish plugin instead: https://developer.android.com/studio/build/maven-publish-plugin
