### ISSUE TITLE
Version 3.6.3 of this plugin is incompatible with version 1.4.30 of Kotlin

### ISSUE THREAD

**Issue by adil-hussain-84** [wupdigital/android-maven-publish#45]
I just tried upgrading Kotlin to the latest version (1.4.30) in a couple of my Android library projects which use this plugin and I'm seeing the `publish` and `publishToMavenLocal` Gradle tasks are failing with an error message as follows:

```
Invalid publication 'QuranSDK': multiple artifacts with the identical extension and classifier ('aar', 'null').
```

You can see this error if you clone the [upgrade-kotlin](https://github.com/adil-hussain-84/quran-sdk/tree/upgrade-kotlin) branch of the [quran-sdk](https://github.com/adil-hussain-84/quran-sdk) GitHub repository and run the `publishToMavenLocal` Gradle task.

**Comment by warnyul** [comment]
You should use this one: https://developer.android.com/studio/build/maven-publish-plugin instead.
