### ISSUE TITLE
stopped working on com.android.tools.build:gradle:4.2.0 and gradle 6.7.1

### ISSUE THREAD

**Issue by rohit5ram** [wupdigital/android-maven-publish#46]
I have upgraded my project android build gradle plugin to 4.2.0 and gradle version 6.7.1

from then on I get 
```
Could not determine the dependencies of task
java.lang.NullPointerException (no error message)
```

I use `classpath 'digital.wup:android-maven-publish:3.6.3'`

**Comment by rohit5ram** [comment]
any update on the fix?

**Comment by Dimon70007** [comment]
the same with com.android.tools.build:gradle:4.2.1. any suggestions or alternatives?

**Comment by trevjonez** [comment]
use the gradle bundled publishing plugin. 
https://developer.android.com/studio/build/maven-publish-plugin

**Comment by Dimon70007** [comment]
ah, thanks. i have already found migrate example - https://github.com/grpc/grpc-java/pull/7842/files
