### ISSUE TITLE
support gradle 4.4

### ISSUE THREAD

**Issue by gunC** [wupdigital/android-maven-publish#9]
[Include all attributes of each variant of a C++ component](https://github.com/gradle/gradle/commit/1786557c9e7cc5d64f59ef0ef743ae891df964e8)

implement `getAttributes()` and `getName()` in `BaseUsage`

**Comment by warnyul** [comment]
4.0.0-SNAPSHOT is available on [oss sonatype](https://oss.sonatype.org/#nexus-search;quick~android-maven-publish)
